# Generated by Django 5.0.6 on 2024-07-13 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите девайс', max_length=255)),
                ('image', models.ImageField(help_text='картинка девайса', upload_to='device_image/')),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Категории Расходов', max_length=255)),
                ('image', models.ImageField(help_text='Картинка категории расходов', upload_to='expenses_image/')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Категории Доходов', max_length=255)),
                ('image', models.ImageField(help_text='Картинка категории доходов', upload_to='income_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Описание расходов', null=True)),
                ('device', models.ForeignKey(help_text='введите девайс которым пользуетесь', on_delete=django.db.models.deletion.CASCADE, to='app.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.expensescategory')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Описание доходов', null=True)),
                ('device', models.ForeignKey(help_text='введите девайс которым пользуетесь', on_delete=django.db.models.deletion.CASCADE, to='app.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.incomecategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='сколько денег вы хотите добавить', max_digits=12)),
                ('picture', models.ImageField(blank=True, help_text='картинка пользователя * необезательно', null=True, upload_to='profile/')),
                ('date_of_birth', models.DateField(help_text='Дата рождения')),
                ('address', models.CharField(blank=True, help_text='Адрес * необезательно', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Номер телефона * необезательно', max_length=15, null=True)),
                ('bio', models.TextField(help_text='О мне')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', '-')], help_text='Пол', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
